### PR TITLE
Modules/PE-22 - Manage Switcher

### PR DESCRIPTION
**Pull request by danciu**
We can sit together and have a demo of the code if you think it would be useful.

Thanks!

### CODE REVIEW

**Comment by azz0r** [comment]
yes please!

**Comment by danciu** [comment]
let's not merge this just yet - still working on it like 1 hr this morning. Just seen your comment, WFH today but I can demo you the whole changes when we do the next sprint :) cheers

**Comment by danciu** [comment]
:+1:

**Comment by azz0r** [comment]
Are you in tomoz?

**Comment by danciu** [comment]
@azz0r We should also merge this now.

**Pull request merged**
